[package]
name = "server"
version = "0.1.0"
edition = "2021"  # Note: 2024 is not valid, use 2021

[[bin]]
name = "server_m"
path = "src/bin/middleware.rs"

[dependencies]
image = "0.25"
rand = "0.8"
aes-gcm = "0.10"   # For encryption
base64 = "0.22"
hex = "0.4"